In [1]:
import torch

# Torch Tensor Basics

In [2]:
# This is a 1-D Tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [3]:
# This is a 2-D Tensor
b = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(b)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


In [4]:
# The size of the tensors
print(a.shape)
print(a.size())
print(b.shape)
print(b.size())

torch.Size([3])
torch.Size([3])
torch.Size([4, 3])
torch.Size([4, 3])


In [5]:
# Get the height/number of rows of b
print(b.shape[0])

4


In [6]:
# Create a float tensor
c = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], dtype = torch.float)
# or we can do
# c = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [7]:
# Create a float tensor
d = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], dtype = torch.double)
# or we can do
# d = torch.DoubleTensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [8]:
print(c.mean())
print(c.std())

tensor(6.5000)
tensor(3.6056)


In [9]:
print(c)
print(c.dtype)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
torch.float32


In [10]:
print(d)
print(d.dtype)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]], dtype=torch.float64)
torch.float64


## Tensor Initialization

In [11]:
# Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)
print(r.dtype)

tensor([[0.7232, 0.2000, 0.8025, 0.5441],
        [0.2298, 0.8392, 0.7807, 0.1820],
        [0.5059, 0.4379, 0.5938, 0.7353],
        [0.8139, 0.9399, 0.6380, 0.5788]])
torch.float32


In [12]:
# Create a matrix with random numbers taken from a normal distribution with mean 0 and standard deviation 1
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[-0.9364, -0.9244, -1.8114,  0.9051],
        [-0.0653,  1.3530, -0.6328, -1.8371],
        [ 0.7593,  0.7205, -0.6417, -0.8433],
        [-0.9931,  1.7660, -0.7124, -0.1129]])
torch.float32


In [13]:
# Create an array of 5 random integers from values between 6 and 9
r3 = torch.randint(6,10,(4,4))
print(r3)
print(r3.dtype)

tensor([[9, 8, 8, 7],
        [9, 9, 6, 7],
        [6, 7, 8, 7],
        [6, 7, 6, 8]])
torch.int64


In [14]:
# Get the number of elements in r, r2, and r3
print(torch.numel(r))
print(torch.numel(r2))
print(torch.numel(r3))


16
16
16


In [15]:
# Construct a 3x3 matrix of zeros and of dtype long
z = torch.zeros( 3, 3, dtype=torch.long)
print(z)
print(z.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.int64


In [16]:
# Construct a 3x3 matrix of ones
o = torch.ones(3,3)
print(o)
print(o.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [17]:
# Create an array with normal distrubution values in the shape of another tensor
r2_like = torch.randn_like(r2, dtype=torch.double)
print(r2_like)


tensor([[ 0.1567,  0.8186,  0.3715, -0.6890],
        [ 0.8030,  0.5178, -0.6878,  0.1625],
        [-0.8676,  0.7637, -0.4857,  0.3023],
        [-1.8072, -0.2084,  0.1049,  0.3496]], dtype=torch.float64)


## Tensor Manipulation

In [18]:
# Note: if one of the dimensions is -1, its size can be inferred
print(b.view(-1, 1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [19]:
# Assign b a new shape
b = b.view(1, -1)
print(b)
print(b.shape)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
torch.Size([1, 12])


In [20]:
# Create a 3D Tensor with 2 channels, 3 rowss, and 4 columns (channels, rows, columns)
threeDim = torch.randn(2,3,4)
print(threeDim)
print(threeDim.view(2,12))
print(threeDim.view(2,-1))

tensor([[[ 0.9376, -0.4923,  1.2839,  0.2516],
         [ 0.9579, -1.1537,  1.3764,  0.2164],
         [-0.1496, -1.8606, -1.1737,  0.3161]],

        [[-0.6614,  0.0222, -0.4623,  1.3141],
         [ 0.4539,  3.1209,  0.5449,  0.0131],
         [ 0.5157, -0.4541,  0.7756, -0.4263]]])
tensor([[ 0.9376, -0.4923,  1.2839,  0.2516,  0.9579, -1.1537,  1.3764,  0.2164,
         -0.1496, -1.8606, -1.1737,  0.3161],
        [-0.6614,  0.0222, -0.4623,  1.3141,  0.4539,  3.1209,  0.5449,  0.0131,
          0.5157, -0.4541,  0.7756, -0.4263]])
tensor([[ 0.9376, -0.4923,  1.2839,  0.2516,  0.9579, -1.1537,  1.3764,  0.2164,
         -0.1496, -1.8606, -1.1737,  0.3161],
        [-0.6614,  0.0222, -0.4623,  1.3141,  0.4539,  3.1209,  0.5449,  0.0131,
          0.5157, -0.4541,  0.7756, -0.4263]])


In [21]:
# Add two tensors (need to be same size and data type)
add_result = torch.add(r, r2)
print(add_result)

tensor([[-0.2132, -0.7244, -1.0089,  1.4492],
        [ 0.1645,  2.1922,  0.1479, -1.6552],
        [ 1.2652,  1.1584, -0.0479, -0.1080],
        [-0.1792,  2.7058, -0.0744,  0.4658]])


In [22]:
# In-place addition (change value of r2)
r2.add_(r)
print(r2)

tensor([[-0.2132, -0.7244, -1.0089,  1.4492],
        [ 0.1645,  2.1922,  0.1479, -1.6552],
        [ 1.2652,  1.1584, -0.0479, -0.1080],
        [-0.1792,  2.7058, -0.0744,  0.4658]])


In [23]:
# Slicing
print(r2[:,1]) # All the rows in the first column
print(r2[:,:2]) # All the rows in the first 2 columns
print(r2[:3,:]) # All the columns in the first 3 rows

tensor([-0.7244,  2.1922,  1.1584,  2.7058])
tensor([[-0.2132, -0.7244],
        [ 0.1645,  2.1922],
        [ 1.2652,  1.1584],
        [-0.1792,  2.7058]])
tensor([[-0.2132, -0.7244, -1.0089,  1.4492],
        [ 0.1645,  2.1922,  0.1479, -1.6552],
        [ 1.2652,  1.1584, -0.0479, -0.1080]])


In [24]:
num_ten = r2[2,3] # element in third row fourth column
print(num_ten)
print(num_ten.item())
print(r2[2,:]) # All columns in second row

tensor(-0.1080)
-0.1079864501953125
tensor([ 1.2652,  1.1584, -0.0479, -0.1080])


In [25]:
# Moving tensor to GPU
print(torch.cuda.is_available())
#r2 = r2.cuda()

False


## Numpy Bridge

In [26]:
import numpy as np

In [27]:
# Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

# Updating one updates the other
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [28]:
# Convert NumPy Array to Torch Tensor
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [29]:
# Converting a list to a tensor
a = [1,2,3,4]
print(a)
to_list = torch.tensor(a)
print(to_list, to_list.dtype)

[1, 2, 3, 4]
tensor([1, 2, 3, 4]) torch.int64


## Tensor Concatenation

In [30]:
# Tensor Concatenation
first1 = torch.randn(2,5)
print(first1)
second1 = torch.randn(3,5)
print(second1)

# Concatenate along the 0 dimension (concatenate rows)
con1 = torch.cat([first1, second1])
print('\n')
print(con1)
print('\n')

first2 = torch.randn(2,3)
print(first2)
second2 = torch.randn(2,5)
print(second2)

# Concatenate along the 1 dimension (concatenate columns)
con2 = torch.cat([first2,second2],1)
print('\n')
print(con2)
print('\n')

tensor([[-1.6266,  1.4577, -0.5604,  1.2156, -2.0893],
        [ 0.8623,  0.5005,  0.7830, -0.8035,  0.2946]])
tensor([[-0.5084,  0.3819, -0.1100, -2.0726, -1.5440],
        [ 1.7129,  0.5353,  0.3998,  0.7815, -0.3566],
        [-0.3904,  0.9411,  0.1379,  0.7167, -0.3691]])


tensor([[-1.6266,  1.4577, -0.5604,  1.2156, -2.0893],
        [ 0.8623,  0.5005,  0.7830, -0.8035,  0.2946],
        [-0.5084,  0.3819, -0.1100, -2.0726, -1.5440],
        [ 1.7129,  0.5353,  0.3998,  0.7815, -0.3566],
        [-0.3904,  0.9411,  0.1379,  0.7167, -0.3691]])


tensor([[ 0.2538, -0.2923,  0.4354],
        [ 0.1504, -0.0289,  1.5242]])
tensor([[-0.2708,  1.2894,  0.3511, -1.2398,  0.7320],
        [ 0.1815, -0.4223, -0.5488, -0.3038,  0.2444]])


tensor([[ 0.2538, -0.2923,  0.4354, -0.2708,  1.2894,  0.3511, -1.2398,  0.7320],
        [ 0.1504, -0.0289,  1.5242,  0.1815, -0.4223, -0.5488, -0.3038,  0.2444]])




## Adding Dimensions

In [31]:
# Adding dimensions of 1 along a specified index
tensor1 = torch.tensor([1,2,3,4])
tensor2 = torch.unsqueeze(tensor1, 0)
print(tensor1)
print(tensor1.shape)
print(tensor2)
print(tensor2.shape)

tensor([1, 2, 3, 4])
torch.Size([4])
tensor([[1, 2, 3, 4]])
torch.Size([1, 4])


## AutoGrad

In [32]:
x = torch.tensor([1., 2., 3], requires_grad=True)
y = torch.tensor([4., 5., 6], requires_grad=True)

# Since x and y have required_grad set to true, we can computer gradients with respect to them
z = x + y
print(z)

# z knows that is was created as a result of addition of x and y
print(z.grad_fn)

s = z.sum()
print(s)
print(s.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)
tensor(21., grad_fn=<SumBackward0>)


In [33]:
# If we backpropagate on s, we can find the gradients of s with respect to x
s.backward()
print(x.grad)

tensor([1., 1., 1.])
