<a href="https://colab.research.google.com/github/nathan-barry/ml-studies/blob/main/pytorch-basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# Torch Tensor Basics

In [5]:
# This is a 1-D Tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [10]:
# This is a 2-D Tensor
b = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(b)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


In [11]:
# The size of the tensors
print(a.shape)
print(a.size())
print(b.shape)
print(b.size())

torch.Size([3])
torch.Size([3])
torch.Size([4, 3])
torch.Size([4, 3])


In [12]:
# Get the height/number of rows of b
print(b.shape[0])

4


In [20]:
# Create a float tensor
c = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], dtype = torch.float)
# or we can do
# c = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [21]:
# Create a float tensor
d = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], dtype = torch.double)
# or we can do
# d = torch.DoubleTensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [25]:
print(c.mean())
print(c.std())

tensor(6.5000)
tensor(3.6056)


In [24]:
print(c)
print(c.dtype)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
torch.float32
tensor(6.5000)


In [26]:
print(d)
print(d.dtype)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]], dtype=torch.float64)
torch.float64


## Tensor Manipulation

In [30]:
# Note: if one of the dimensions is -1, its size can be inferred
print(b.view(-1, 1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [31]:
# Assign b a new shape
b = b.view(1, -1)
print(b)
print(b.shape)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
torch.Size([1, 12])


In [32]:
# Create a 3D Tensor with 2 channels, 3 rowss, and 4 columns (channels, rows, columns)
threeDim = torch.randn(2,3,4)
print(threeDim)
print(threeDim.view(2,12))
print(threeDim.view(2,-1))

tensor([[[ 0.3315,  0.9033, -0.0766, -0.2915],
         [-1.2961,  2.4202,  0.9670, -2.1355],
         [ 1.6384,  0.3926,  0.5072, -1.0948]],

        [[-0.6069,  0.6137,  0.0811,  0.0184],
         [ 0.7636, -1.0226, -0.1317,  1.3183],
         [ 0.0954,  1.2228,  2.2105, -0.4530]]])
tensor([[ 0.3315,  0.9033, -0.0766, -0.2915, -1.2961,  2.4202,  0.9670, -2.1355,
          1.6384,  0.3926,  0.5072, -1.0948],
        [-0.6069,  0.6137,  0.0811,  0.0184,  0.7636, -1.0226, -0.1317,  1.3183,
          0.0954,  1.2228,  2.2105, -0.4530]])
tensor([[ 0.3315,  0.9033, -0.0766, -0.2915, -1.2961,  2.4202,  0.9670, -2.1355,
          1.6384,  0.3926,  0.5072, -1.0948],
        [-0.6069,  0.6137,  0.0811,  0.0184,  0.7636, -1.0226, -0.1317,  1.3183,
          0.0954,  1.2228,  2.2105, -0.4530]])


## Tensor Initialization

In [36]:
# Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)
print(r.dtype)

tensor([[0.1963, 0.0841, 0.5276, 0.2430],
        [0.9413, 0.9931, 0.6290, 0.5057],
        [0.1185, 0.8951, 0.6938, 0.0351],
        [0.6681, 0.3561, 0.6406, 0.5741]])
torch.float32


In [34]:
# Create a matrix with random numbers taken from a normal distribution with mean 0 and standard deviation 1
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[ 1.4306, -1.0290,  1.5422,  1.3072],
        [ 1.1015, -0.0147, -0.1567,  0.7905],
        [-0.4253, -0.7976,  0.6186, -1.6076],
        [ 0.3784,  1.8727, -0.4174, -0.7044]])
torch.float32


In [45]:
# Create an array of 5 random integers from values between 6 and 9
r3 = torch.randint(6,10,(4,4))
print(r3)
print(r3.dtype)

tensor([[8, 9, 7, 9],
        [6, 8, 8, 9],
        [8, 7, 9, 6],
        [8, 7, 8, 6]])
torch.int64


In [47]:
# Get the number of elements in r, r2, and r3
print(torch.numel(r))
print(torch.numel(r2))
print(torch.numel(r3))


16
16
16


In [48]:
# Construct a 3x3 matrix of zeros and of dtype long
z = torch.zeros( 3, 3, dtype=torch.long)
print(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
