<a href="https://colab.research.google.com/github/nathan-barry/ml-studies/blob/main/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

# Torch Tensor Basics

In [4]:
# This is a 1-D Tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [5]:
# This is a 2-D Tensor
b = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(b)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


In [6]:
# The size of the tensors
print(a.shape)
print(a.size())
print(b.shape)
print(b.size())

torch.Size([3])
torch.Size([3])
torch.Size([4, 3])
torch.Size([4, 3])


In [7]:
# Get the height/number of rows of b
print(b.shape[0])

4


In [8]:
# Create a float tensor
c = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], dtype = torch.float)
# or we can do
# c = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [9]:
# Create a float tensor
d = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], dtype = torch.double)
# or we can do
# d = torch.DoubleTensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [10]:
print(c.mean())
print(c.std())

tensor(6.5000)
tensor(3.6056)


In [11]:
print(c)
print(c.dtype)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
torch.float32


In [12]:
print(d)
print(d.dtype)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]], dtype=torch.float64)
torch.float64


## Tensor Initialization

In [13]:
# Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)
print(r.dtype)

tensor([[0.7602, 0.6852, 0.7017, 0.9714],
        [0.0299, 0.8238, 0.4363, 0.5167],
        [0.2306, 0.7675, 0.6680, 0.6472],
        [0.5027, 0.9534, 0.1679, 0.2440]])
torch.float32


In [14]:
# Create a matrix with random numbers taken from a normal distribution with mean 0 and standard deviation 1
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[-0.7828, -0.9622, -0.0321, -1.0123],
        [-0.8095, -0.5969, -0.4574, -1.3692],
        [-0.2386, -0.0889,  0.7155, -2.2447],
        [ 0.5511,  1.8452,  1.1265,  0.9201]])
torch.float32


In [15]:
# Create an array of 5 random integers from values between 6 and 9
r3 = torch.randint(6,10,(4,4))
print(r3)
print(r3.dtype)

tensor([[7, 9, 8, 8],
        [8, 6, 9, 7],
        [7, 7, 8, 6],
        [9, 9, 6, 6]])
torch.int64


In [16]:
# Get the number of elements in r, r2, and r3
print(torch.numel(r))
print(torch.numel(r2))
print(torch.numel(r3))


16
16
16


In [17]:
# Construct a 3x3 matrix of zeros and of dtype long
z = torch.zeros( 3, 3, dtype=torch.long)
print(z)
print(z.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.int64


In [18]:
# Construct a 3x3 matrix of ones
o = torch.ones(3,3)
print(o)
print(o.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [19]:
# Create an array with normal distrubution values in the shape of another tensor
r2_like = torch.randn_like(r2, dtype=torch.double)
print(r2_like)


tensor([[-0.0949, -0.0719, -0.8928,  0.8732],
        [ 0.2456,  0.0234,  0.9693, -0.1658],
        [ 0.4485,  0.5590, -0.7979,  0.5977],
        [-0.3334, -1.3010, -0.0693,  0.6398]], dtype=torch.float64)


## Tensor Manipulation

In [20]:
# Note: if one of the dimensions is -1, its size can be inferred
print(b.view(-1, 1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [21]:
# Assign b a new shape
b = b.view(1, -1)
print(b)
print(b.shape)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
torch.Size([1, 12])


In [22]:
# Create a 3D Tensor with 2 channels, 3 rowss, and 4 columns (channels, rows, columns)
threeDim = torch.randn(2,3,4)
print(threeDim)
print(threeDim.view(2,12))
print(threeDim.view(2,-1))

tensor([[[ 1.0480, -0.2369,  1.3260,  0.5558],
         [ 1.0357, -0.2684,  1.5332,  1.2223],
         [-0.5484,  0.8098, -0.7245, -0.5128]],

        [[-0.4894, -1.7492, -0.4508, -0.9753],
         [-1.3272, -1.2372, -0.5702,  1.6642],
         [ 0.5156,  1.1326,  0.7150, -0.0244]]])
tensor([[ 1.0480, -0.2369,  1.3260,  0.5558,  1.0357, -0.2684,  1.5332,  1.2223,
         -0.5484,  0.8098, -0.7245, -0.5128],
        [-0.4894, -1.7492, -0.4508, -0.9753, -1.3272, -1.2372, -0.5702,  1.6642,
          0.5156,  1.1326,  0.7150, -0.0244]])
tensor([[ 1.0480, -0.2369,  1.3260,  0.5558,  1.0357, -0.2684,  1.5332,  1.2223,
         -0.5484,  0.8098, -0.7245, -0.5128],
        [-0.4894, -1.7492, -0.4508, -0.9753, -1.3272, -1.2372, -0.5702,  1.6642,
          0.5156,  1.1326,  0.7150, -0.0244]])


In [23]:
# Add two tensors (need to be same size and data type)
add_result = torch.add(r, r2)
print(add_result)

tensor([[-0.0226, -0.2770,  0.6695, -0.0409],
        [-0.7796,  0.2269, -0.0210, -0.8525],
        [-0.0079,  0.6786,  1.3834, -1.5975],
        [ 1.0538,  2.7985,  1.2944,  1.1642]])


In [24]:
# In-place addition (change value of r2)
r2.add_(r)
print(r2)

tensor([[-0.0226, -0.2770,  0.6695, -0.0409],
        [-0.7796,  0.2269, -0.0210, -0.8525],
        [-0.0079,  0.6786,  1.3834, -1.5975],
        [ 1.0538,  2.7985,  1.2944,  1.1642]])


In [25]:
# Slicing
print(r2[:,1]) # All the rows in the first column
print(r2[:,:2]) # All the rows in the first 2 columns
print(r2[:3,:]) # All the columns in the first 3 rows

tensor([-0.2770,  0.2269,  0.6786,  2.7985])
tensor([[-0.0226, -0.2770],
        [-0.7796,  0.2269],
        [-0.0079,  0.6786],
        [ 1.0538,  2.7985]])
tensor([[-0.0226, -0.2770,  0.6695, -0.0409],
        [-0.7796,  0.2269, -0.0210, -0.8525],
        [-0.0079,  0.6786,  1.3834, -1.5975]])


In [26]:
num_ten = r2[2,3] # element in third row fourth column
print(num_ten)
print(num_ten.item())
print(r2[2,:]) # All columns in second row

tensor(-1.5975)
-1.597470998764038
tensor([-0.0079,  0.6786,  1.3834, -1.5975])


In [34]:
# Moving tensor to GPU
print(torch.cuda.is_available())
#r2 = r2.cuda()

False


## Numpy Bridge

In [27]:
import numpy as np

In [29]:
# Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

# Updating one updates the other
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [31]:
# Convert NumPy Array to Torch Tensor
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [36]:
# Converting a list to a tensor
a = [1,2,3,4]
print(a)
to_list = torch.tensor(a)
print(to_list, to_list.dtype)

[1, 2, 3, 4]
tensor([1, 2, 3, 4]) torch.int64


## Tensor Concatenation

In [41]:
# Tensor Concatenation
first1 = torch.randn(2,5)
print(first1)
second1 = torch.randn(3,5)
print(second1)

# Concatenate along the 0 dimension (concatenate rows)
con1 = torch.cat([first1, second1])
print('\n')
print(con1)
print('\n')

first2 = torch.randn(2,3)
print(first2)
second2 = torch.randn(2,5)
print(second2)

# Concatenate along the 1 dimension (concatenate columns)
con2 = torch.cat([first2,second2],1)
print('\n')
print(con2)
print('\n')

tensor([[ 0.1549, -1.5662,  1.9940,  0.4466,  2.1681],
        [-2.6334, -0.6831, -0.0817,  0.0984,  1.1853]])
tensor([[-2.2453, -0.4524,  0.2878,  0.6334,  0.2179],
        [-0.2130, -0.3381,  1.4571, -1.6605, -0.5488],
        [ 0.5372, -0.0036,  0.9148,  2.4683, -1.8653]])


tensor([[ 0.1549, -1.5662,  1.9940,  0.4466,  2.1681],
        [-2.6334, -0.6831, -0.0817,  0.0984,  1.1853],
        [-2.2453, -0.4524,  0.2878,  0.6334,  0.2179],
        [-0.2130, -0.3381,  1.4571, -1.6605, -0.5488],
        [ 0.5372, -0.0036,  0.9148,  2.4683, -1.8653]])


tensor([[-1.8240,  1.5482,  0.5836],
        [ 0.6046,  0.6958, -0.2904]])
tensor([[-0.5139,  0.0788, -1.3835, -1.4164,  0.8374],
        [ 0.4235,  0.3307,  0.5667, -1.0839,  0.1657]])


tensor([[-1.8240,  1.5482,  0.5836, -0.5139,  0.0788, -1.3835, -1.4164,  0.8374],
        [ 0.6046,  0.6958, -0.2904,  0.4235,  0.3307,  0.5667, -1.0839,  0.1657]])




## Adding Dimensions

In [42]:
# Adding dimensions of 1 along a specified index
tensor1 = torch.tensor([1,2,3,4])
tensor2 = torch.unsqueeze(tensor1, 0)
print(tensor1)
print(tensor1.shape)
print(tensor2)
print(tensor2.shape)

tensor([1, 2, 3, 4])
torch.Size([4])
tensor([[1, 2, 3, 4]])
torch.Size([1, 4])


## AutoGrad

In [45]:
x = torch.tensor([1., 2., 3], requires_grad=True)
y = torch.tensor([4., 5., 6], requires_grad=True)

# Since x and y have required_grad set to true, we can computer gradients with respect to them
z = x + y
print(z)

# z knows that is was created as a result of addition of x and y
print(z.grad_fn)

s = z.sum()
print(s)
print(s.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)
tensor(21., grad_fn=<SumBackward0>)


In [46]:
# If we backpropagate on s, we can find the gradients of s with respect to x
s.backward()
print(x.grad)

tensor([1., 1., 1.])
